### ISSUE TITLE
Error while running helper function

### ISSUE THREAD

**Issue by unagi2020** [nknapp/promised-handlebars#37]
I am getting follwoing error when used with bluebird. Please help.

Debug: internal, implementation, error 
    Error: Missing helper: "message"
    at Object.<anonymous> (/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
    at Object.eval [as main] (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:117)
    at main (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at Object.ret (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at Object.ret [as views/components/sidebar/my] (/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at Object.invokePartialWrapper [as invokePartial] (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46)
    at eval (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at Object.prog [as fn] (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at Object.<anonymous> (/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:19:22)
    at Object.eval [as main] (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:11:32)
    at main (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at Object.ret (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at Object.ret [as views/type/appformtagpage] (/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at Object.invokePartialWrapper [as invokePartial] (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46)
    at eval (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at Object.prog [as fn] (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at Object.<anonymous> (/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:19:22)
    at Object.eval [as main] (eval at createFunctionContext (/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:35)
    at main (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at ret (/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at Object.renderer (/node_modules/vision/lib/manager.js:141:36)

**Comment by Gottwik** [comment]
Could you share the code how you register the `message` helper?

**Comment by unagi2020** [comment]
Sure, here is the code ....


`const handlebars         = require('handlebars');`
`const promisedHandlebars = require('promised-handlebars');
`
`const pHandlebars             = promisedHandlebars(require('handlebars'), { Promise: require('bluebird') });`
``
``
`pHandlebars.registerHelper('message', function(id) {`
`  MessageModel.findOne({_id: id}, function (err, obj) {`
`   return obj.subject;`
`  })`
`})`

Following are npm versions
"bluebird": "^3.5.0",
"promised-handlebars": "^2.0.1",
"handlebars": "^4.0.10",

**Comment by Gottwik** [comment]
looks ok, are you sure you are using the same `pHandlebars` when rendering stuff? Is it all in the same file? I suspect you might be registering the helper somewhere and then using another instance of it.

**Comment by unagi2020** [comment]
All are in the same file. I am struggling to make it for couple of days now. I have about 50 other regular helpers in the same file and all expect this promised helper work fine. I am using it with Node 8.4.0 and HAPI 16.5.1

**Comment by nknapp** [comment]
I think you are mixing promises and callbacks. The helper must return a promise, but yours is only returning value from within the callback.

Try the "pify" package or use "new Promise(...)" As return value.

**Comment by nknapp** [comment]
Not sure if this is really the cause of the problem though.

**Comment by unagi2020** [comment]
I get the same error when I return a string instead of resultset.

**Comment by Gottwik** [comment]
did you fix it?

**Comment by unagi2020** [comment]
Not yet. Was distracted by other issues.  Will get some time today to debug the problem today.
