### ISSUE TITLE
Cannot read property 'toHTML' of undefined

### ISSUE THREAD

**Issue by tiholic** [nknapp/promised-handlebars#39]
Encountered these logs. Unable to find the root cause.

```py
TypeError: Cannot read property 'toHTML' of undefined
    at replacePlaceholdersRecursivelyIn (.../node_modules/promised-handlebars/lib/markers.js:96:31)
    at .../node_modules/promised-handlebars/lib/markers.js:106:22
    at .../node_modules/promised-handlebars/lib/replaceP.js:44:47
    at String.replace (<anonymous>)
    at replaceP (.../node_modules/promised-handlebars/lib/replaceP.js:37:14)
    at replacePlaceholdersRecursivelyIn (.../node_modules/promised-handlebars/lib/markers.js:102:20)
    at .../node_modules/promised-handlebars/lib/markers.js:111:18
```

PS: Thank you for the work. This package is a great relief!

**Comment by tiholic** [comment]
Found the root cause: One of my `async` helpers was returning `undefined` in one particular scenario.
